### ISSUE TITLE
Error in localized-numbers.module.d.ts with Angular 10 core

### ISSUE THREAD

**Issue by Gargano83** [mbenzenhoefer/ngx-localized-numbers#6]
Greetings,
this is my package.json file:
`{
  "name": "koncentro-gui-v10",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular-slider/ngx-slider": "^2.0.3",
    "@angular/animations": "~10.0.0",
    "@angular/common": "~10.0.0",
    "@angular/compiler": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/platform-server": "^12.2.9",
    "@angular/router": "~10.0.0",
    "@angularclass/hmr": "^3.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@types/geojson": "^7946.0.8",
    "@types/jquery": "^3.5.6",
    "angular-2-local-storage": "^3.0.2",
    "angular2-highcharts": "^0.5.5",
    "angular2-query-builder": "^0.6.2",
    "animate.css": "^4.1.1",
    "chart.js": "^3.5.1",
    "core-js": "^3.18.2",
    "d3-array": "^3.1.1",
    "file-saver": "^2.0.5",
    "font-awesome": "^4.7.0",
    "fullcalendar": "^5.9.0",
    "geojson": "^0.5.0",
    "gzip-all": "^1.0.0",
    "highcharts": "^9.2.2",
    "jquery": "^3.6.0",
    "jsbarcode": "^3.11.5",
    "moment": "^2.29.1",
    "nanoscroller": "^0.8.7",
    "ng2-dragula": "^2.1.1",
    "ngx-localized-numbers": "^0.3.1",
    "ngx-schema-form": "^2.6.6",
    "node-sass": "^4.14.1",
    "pg": "^8.7.1",
    "primeicons": "^4.1.0",
    "primeng": "^6.0.2",
    "quill": "^1.3.7",
    "rxjs": "~6.5.5",
    "ts-helpers": "^1.1.2",
    "tslib": "^2.0.0",
    "uuid": "^8.3.2",
    "venn.js": "^0.2.20",
    "xlsx": "^0.17.2",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/cli": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@angular/language-service": "^12.2.9",
    "@types/angular": "^1.8.3",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^6.0.101",
    "codelyzer": "^6.0.0-next.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}`

I am trying to compile the project with the **ng-serve** command but I am getting this error:
![image](https://user-images.githubusercontent.com/17437215/136773414-871ebda5-ee09-42cd-9e31-703246f4fa8e.png)

Can you help me?

Thanks.

**Comment by mbenzenhoefer** [comment]
@Gargano83 sorry for the late reply. I just published version `1.0.0` which uses @angular/cli for building the library. Now everything should work fine :-)
